#!/usr/bin/php -d variables_order=EGPCS
<?php

# make sure errors go to stderr
ini_set('log_errors', 1);
ini_set('error_log', 'syslog');
ini_set('display_errors', 'stderr' );

require_once __DIR__.'/CliHandler.php';
require_once __DIR__.'/Client.php';
require_once __DIR__.'/Cli.php';
require_once __DIR__.'/../Rest/Client.php';
require_once __DIR__.'/../Server/Helper/SyntacticSugar.php';

exit(Ric_Client_CliHandler::handleExecute($argv, $_ENV, file_get_contents(__DIR__.'/README.md'))); // command line status


